metadata:
    logo: img/coffee_icon.png
    tagline: Min Mvc Me-sida
    social:
        - title: The web site's repo on GitHub.
          url: https://github.com/RunningStrings/design2023
          icon: fab fa-github
        - title: Instagram
          url: https://instagram.com/annievgu/
          icon: fab fa-instagram
