metadata:
    websitename: 'Mvc - Annie'
    logo: img/coffee_icon.png
    tagline: Objektorienterade webbteknologier (mvc v2)
    social:
        - title: Webbsidans repo på Github.
          url: https://github.com/RunningStrings/mvc-report
          icon: fab fa-github
        - title: Instagram
          url: https://instagram.com/annievgu/
          icon: fab fa-instagram
