quotes:
  - text: "The only way to do great work is to love what you do."
    author: "Steve Jobs"
  - text: "Success is not final, failure is not fatal: It is the courage to continue that counts."
    author: "Winston Churchill"
  - text: "Without leaps of imagination or dreaming, we lose the excitement of possibilities. Dreaming, after all is a form of planning."
    author: "Gloria Steinem"
  - text: "A man who carries a cat by the tail learns something he can learn in no other way."
    author: "Mark Twain"
  - text: "Try to imagine all life as you know it stopping instantaneously and every molecule in your body exploding at the speed of light."
    author: "Egon Spengler"
  - text: "Love is awful. It's painful. It's frightening. It makes you doubt yourself, judge yourself, distance yourself from the other people in your life. It makes you selfish. It makes you creepy. It makes you obsessed with your hair. It makes you cruel. It makes you say and do things you never thought you would do."
    author: "Fleabag"